### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by JonathanHelianthicusDoe** [open-toontown/open-toontown#1]
**Usual disclaimers: IANAL, TINLA, &amp;c.**

I hate to be a nit-picky jerk, but I think this is particularly important in this case: currently it appears that you don&rsquo;t have any licensing information anywhere in the repo. Thanks to [the Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention), this effectively makes your code *not* [open source](https://opensource.org/osd), but merely &ldquo;source-available&rdquo;. In order to ensure that your code is actually open source, you&rsquo;ll need to pick a license. Ideally the license should be [approved by the OSI](https://opensource.org/licenses/category) and also [approved by the FSF and GPL-compatible](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

If I had to make a recommendation (again, just a recommendation), I would suggest the [BSD 3-clause license](https://opensource.org/licenses/BSD-3-Clause), because

* Panda3D and Astron already use this license.
* The OSI lists it under &ldquo;Licenses that are &lsquo;popular and widely-used or with strong communities&rsquo;&rdquo;.
* It is FSF-approved and GPL-compatible.

For the things in here that are not code, but are just resources that are (I assume) actually Disney&rsquo;s assets (stuff in phase files, whatever), I would recommend at least giving a disclaimer in the README that these certain assets *belong to Disney.* Even better would be to move them entirely into their own separate repositor(y/ies) and then only give users of Open Toontown a bit of a &ldquo;nudge&rdquo; towards that repository, saying that it consists entirely of Disney&rsquo;s assets and thus *distance Open Toontown from that content* (for the obvious legal reasons).

Additionally, I can see that there are probably some other binary blobs in here that are actually code (for example, the `libpandadna.so` in the root directory). I&rsquo;m sure that (or at least, I hope that) these things have their corresponding source code elsewhere in the Open Toontown GitHub organization, but still, it would be nice to be super crisp and clear about where each corresponding source code is, how to reproduce the binaries, &amp;c. Of course, ideally you shouldn&rsquo;t really have binary blobs in source code repos anyways if you can avoid it without causing too much trouble.

**Comment by nahboi** [comment]
Then why ttr opd ti ttcc gets their assets from deer comrade
Jesse And Disney interactive doesnt care.
we need to move on stuff.
what if it was archive do it need license ?
what if it was code the owner was made hm?
question here we dont need license here.
thats seems a little bit ironic even cats are better than you.
you cant get your own nose  that tell people to do stuff.
Sorcerer mom.
**_dont question below thanks bye!_**

**Comment by opentoontown** [comment]
Thank you so much for your suggestions here! You are definitely not being a "nit-picky jerk," and I would hope that others would not interpret you as such!

Indeed, it is super important that we get some form of licensing setup for the Open Toontown project. I definitely thought about how the project would be licensed before I even started the project, but never really decided on a particular license. I just knew that whatever license I were to choose, I would want to be as nonrestrictive as possible. As you said, getting a license in place for a project like this is super important in order for it to actually be open source, and it should probably be taken care of sooner rather than later. Being that all the current progress in this particular repository follows along with the livestreams that I have been hosting to show the process along the way, I immediately began working on the game itself without getting into licensing and all the nitty-gritty stuff like that on stream. Having said that, I aim to address the licensing later today.

Per your suggestions, we are going to be implementing the BSD 3-clause license across all repositories that we ourselves have created, with the exception of the resources repository, which I will also talk briefly about. This includes, but is not limited to, https://github.com/open-toontown/open-toontown, https://github.com/open-toontown/libtoontown-pets, https://github.com/open-toontown/libotp-movement, and (probably) https://github.com/open-toontown/toontown-online-2013-decompiled. The remainder of our current repositories are forks, and of course will retain the chosen licenses of their respective creators/maintainers.

Again, per your suggestions, the Disney assets contained within the `resources` directory in this repository will be removed from this repository entirely, and will be moved into their own respective repository, with disclaimers, nudges, and everything of the sorts. While it is likely that the resources repository would at some point also contain our own assets of some form, the majority of those assets are also pretty much guaranteed to always be the sole property of Disney, so this is the best course of action, and one that I considered initially but also initially decided against in the name of convenience, but one that I am stepping back on in order to save myself and the project in the long-term.

Additionally, binary blobs will also be removed from this repository, which at this current point in time is only `libpandadna.so`, but I digress. We do indeed host the source code for libpandadna on our own Open Toontown organization, which can be found here: https://github.com/open-toontown/libpandadna, though this is merely a fork of the original repository, which can be found here: https://github.com/loblao/libpandadna

Again, thank you for your suggestions! :)

**Comment by JonathanHelianthicusDoe** [comment]
> [&hellip;], and (probably) [https://github.com/open-toontown/toontown-online-2013-decompiled](https://github.com/open-toontown/toontown-online-2013-decompiled).

So, maybe this belongs in an issue in that repository specifically, but I have&hellip; worries about the decompilation. If it is not *just* a decompilation of the object code and is *actually reverse-engineered*, then I don&rsquo;t think that any of my concerns here are relevant <sub>(disregarding possible patents)</sub>. But I assume this stuff is just decompiled since presumably Disney distributed the stuff as Python bytecode, which I&rsquo;m sure is pretty trivial to decompile.

For comparison, see [this section on Wikipedia&rsquo;s page for ReactOS](https://en.wikipedia.org/wiki/ReactOS#Internal_audit). Maybe I&rsquo;m going a bit too far here, because the United States&rsquo;s requirement that &ldquo;a reimplementation based on disassembled code must be written by someone other than the person having disassembled and examined the original code&rdquo; is, well, more than a little awkward. It is, however, totally possible; clean-room design, again [according to Wikipedia](https://en.wikipedia.org/wiki/Clean_room_design):

> [&hellip;] is [typically] done by having someone examine the system to be reimplemented and having this person write a specification. This specification is then reviewed by a lawyer to ensure that no copyrighted material is included. The specification is then implemented by a team with no connection to the original examiners.

So, the fact that something this elaborate (apparently even involving a lawyer!) is common practice in order to ensure that the resulting code&rsquo;s copyrights belong to the reimplementors (and not the original implementors, a.k.a. Disney in our case) is troubling&hellip; you can&rsquo;t license something that you don&rsquo;t have the copyrights to, obviously.

To back up a little bit, the first thing that I would think to do here is to make sure this stuff is in its own repository (already done, great) and then put a `COPYING` file in the repository (and similar content in the README as well) that makes it clear that the content is not &ldquo;reverse-engineered&rdquo; *per se*, but is decompiled and ultimately belongs to Disney. A key point to stress here is that such decompilations are **for reference only**, and that anyone without the proper copyrights (i.e. anyone not authorized by Disney) is strictly *verboten* as far as reusing the code in a way that could not be shown to be a re-implementation (i.e. not reuse at all).

This is without even getting into (possible) problems of [software](https://en.wikipedia.org/wiki/Software_patent) [patents](https://en.wikipedia.org/wiki/Software_patent_debate), which even a fully clean-room engineered re-implementation cannot avoid&hellip; But I&rsquo;m already getting a headache just thinking about it, so I will stop there.

Hopefully this at least covers the legal bases, so to speak. Again, IANAL unless you consider anyone who can read Wikipedia to be a lawyer!

**Comment by opentoontown** [comment]
@JonathanHelianthicusDoe Indeed, the Python source code contained within https://github.com/open-toontown/toontown-online-2013-decompiled (and subsequently this repository) was decompiled, rather than a clean-room reverse engineering of the game itself into comparable Python source code. Put simply, the frozen Python modules were dumped from the Toontown Online client to Python bytecode, and that Python bytecode was then decompiled to Python source code. The process of dumping frozen Python modules to bytecode, and decompiling that bytecode to source code, is a rather trivial process of course. Having said that, it was also necessary for me to fix numerous decompilation errors in the decompiled code prior to uploading it to GitHub, which went beyond a typical Python decompilation process and more into the realm of lower-level reverse-engineering, but I digress. 

So yes, it is a decompile. To be honest with you, I am not entirely sure how to approach this. I understand that I am not in any position to place any of my own licenses on the repository containing the unmodified, decompiled Toontown Online source code, and I’m okay with that. If nothing else, that repository is merely intended to serve as an archival of the original, unmodified code, as well as a reference for anybody who wants it. Having said that, that repository has also served as a starting point for the Open Toontown project. That is, I have been using the decompiled Toontown Online source code as the base for building Open Toontown, and making any necessary changes and/or fixes to bring it up-to-date for modern Panda3D, and usable in the current day. Being that the decompile is just that, and not a clean-room reverse-engineer, I’m already walking on a thin line here, but I also don’t feel as though I have many better options for approaching this. This is perhaps the biggest challenge and/or roadblock for a project such as this, which may be why it hasn’t been attempted previously (to my knowledge). 

The libotp & libtoontown code would be the closest to a clean-room reverse engineer, and even then they aren’t clean-room as those who disassembled the original modules are also the ones who reimplemented it via pseudo code, so it also isn’t a straight decompile. 

This is definitely all within a legal grey area, and perhaps I’m not even in a position to be placing a license on this repository either, as it’s still using decompiled code, just modified.

**Comment by opentoontown** [comment]
I have gone ahead and implemented the BSD 3-clause license across the following repositories: https://github.com/open-toontown/open-toontown, https://github.com/open-toontown/libtoontown-pets, and https://github.com/open-toontown/libotp-movement.

https://github.com/open-toontown/libtoontown-pets and https://github.com/open-toontown/libotp-movement have historically used the MIT license, which is the license chosen by me (jwcotejr) when initially creating these repositories. However, I have ultimately decided to transition those two repositories from the MIT license to the BSD 3-clause license for consistency, and to avoid confusion. From what I have gathered from my admittedly limited research, there are no implications in me making this change in licenses, as I am currently the sole contributor on all of these repositories.

This repository is the only repository that I am rather certain of, as to whether or not I can even be placing any license on it at all, but regardless I am taking a bit of a chance here and hoping that it works out.

**Comment by AnonymousDeveloper65535** [comment]
shouldn't this be closed now since you added the licenses?

**Comment by opentoontown** [comment]
Well yes, but also no. The issue will be considered resolved, and thus will be closed, upon the remainder of the concerns addressed within the issue being taken care of. That is, binary blobs are to be purged from this repository, and the Disney assets are also to be moved to their own dedicated repository, with no license of course.

**Comment by jwcotejr** [comment]
Closing this issue as it is now resolved.
