### ISSUE TITLE
A few technical questions

### ISSUE THREAD

**Issue by ghost** [open-toontown/open-toontown#8]
Not exactly an issue, but here goes.

My first question is, will the game support Direct X rendering, if desired? If I can recall, Direct X rendering under TTO has less issues, compared to OpenGL, so it would be nice to have it back as an option.

My second question is regarding audio. I know audio isnt being worked on for the moment, however, I was recently made aware that the Factories had ambient noises that no longer play. A user named Dank Mickey shows these off in action, and seems to offer code in the description to add this to a server. Here is a link to that: [https://www.youtube.com/watch?v=-IC-9yX97wI&feature=youtu.be](url) So, is it possible to also add this in, once you get around to audio?

**Comment by ghost** [comment]
Oh, and according to this: [https://www.youtube.com/watch?v=rcsYhSHMtT4&feature=youtu.be](url) golfing also had ambient noises? Makes me wonder what other areas have busted ambience.

**Comment by jwcotejr** [comment]
The game already technically supports DirectX 9 rendering, provided your Panda3D SDK is built with support for DirectX 9, and you change `Configrc.prc` to use `load-display pandadx9` rather than `load-display pandagl`.

In regards to your second question, I'm not sure. Open Toontown's current goal is to replicate the latest version of Disney's Toontown Online, and there's not necessarily much focus on reintroducing lost or scrapped content at the moment. This is likely something that someone else would implement on a fork of Open Toontown rather than us doing that.

**Comment by ghost** [comment]
Thanks for responding!

I didn't know Direct X support was already in, so thats cool, and fair enough with keeping things as close to 2013.
